version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    networks:
      - ecommerce-net

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    networks:
      - ecommerce-net

  # other services (admin-service, user-service, etc.)
  # ...

networks:
  ecommerce-net:
    driver: bridge
